[project]
name = "spectral_flux"
version = "0.2.0"
description = "Python tools for calculating spectral flux from fluid velocities"
readme = "README.md"
authors = [{ name = "pcarlip", email = "peter.carlip@proton.me" }]
requires-python = ">=3.13"
dependencies = [
    "cupy-xarray>=0.1.5",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scipy>=1.18.1",
    "xarray>=2026.7.0",
    "xarray-extras>=0.6.0",
    "xrft",
    "xrscipy>=3.1.0",
]
license = "MIT"
license-files = ["LICENSE"]


[project.urls]
Homepage = "https://github.com/pcarlip/spec_flux"
Issues = "https://github.com/pcarlip/spec_flux/issues"

[project.optional-dependencies]
cupy12 = ["cupy-cuda12x"]
cupy13 = ["cupy-cuda13x"]

[tool.uv]
conflicts = [[{ extra = "cuda12" }, { extra = "cuda13" }]]

[project.scripts]
spec-flux = "spec_flux:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
xrft = { git = "https://github.com/pcarlip/xrft.git", branch = "cupy" }
# currently using my own branch of xrft which supports cupy
# will switch to main branch if my PR is accepted

[dependency-groups]
dev = ["ruff>=0.16.5"]
test = ["fluidsf>=0.2.2", "pytest>=9.1.1"]

[tool.ruff]
exclude = [
    ".git",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "venv",
]

line-length = 90
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = [
    "F",
    "B",
    "UP",
    "I",
    "ANN",
    "E",
    "A",
    "C4",
    "ICN",
    "PIE",
    "SIM",
    "PLE",
    "PLC",
    "PLR",
    "PLW",
    "NPY",
    "RUF",
    "PD",
    "PYI",
    "PERF",
    "C",
    "FURB",
]

ignore = [
    "F401",
    "PLR0913",
    "E203",
    "B018",
    "PLR0917",
    "PLR0914",
    "RUF003",
    "PLR0915",
]
fixable = ["ALL"]
unfixable = []


[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
